name: publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js/18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm i
      - name: prettier
        run: npm run prettier
      - name: build
        run: npm run build
      - name: verify
        run: npm run verify

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
